require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/previews", type: :request do
  # Preview. As you add validations to Preview, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Preview.create! valid_attributes
      get previews_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      preview = Preview.create! valid_attributes
      get preview_url(preview)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_preview_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      preview = Preview.create! valid_attributes
      get edit_preview_url(preview)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Preview" do
        expect {
          post previews_url, params: {preview: valid_attributes}
        }.to change(Preview, :count).by(1)
      end

      it "redirects to the created preview" do
        post previews_url, params: {preview: valid_attributes}
        expect(response).to redirect_to(preview_url(Preview.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Preview" do
        expect {
          post previews_url, params: {preview: invalid_attributes}
        }.to change(Preview, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post previews_url, params: {preview: invalid_attributes}
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested preview" do
        preview = Preview.create! valid_attributes
        patch preview_url(preview), params: {preview: new_attributes}
        preview.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the preview" do
        preview = Preview.create! valid_attributes
        patch preview_url(preview), params: {preview: new_attributes}
        preview.reload
        expect(response).to redirect_to(preview_url(preview))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        preview = Preview.create! valid_attributes
        patch preview_url(preview), params: {preview: invalid_attributes}
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested preview" do
      preview = Preview.create! valid_attributes
      expect {
        delete preview_url(preview)
      }.to change(Preview, :count).by(-1)
    end

    it "redirects to the previews list" do
      preview = Preview.create! valid_attributes
      delete preview_url(preview)
      expect(response).to redirect_to(previews_url)
    end
  end
end
